# Generated by Django 5.1.2 on 2024-11-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='სლაგი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(default='Agro Farm', max_length=150, verbose_name='ქვეყანა'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True, verbose_name='სლაგი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='store.producttags', verbose_name='ტეგები'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='თარიღი'),
        ),
        migrations.AlterField(
            model_name='producttags',
            name='tag_name',
            field=models.CharField(max_length=150, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='shopreviews',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='თარიღი'),
        ),
    ]
