# Generated by Django 5.1.2 on 2024-11-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_slug_alter_product_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='აღწერა'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_ka',
            field=models.TextField(blank=True, null=True, verbose_name='აღწერა'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='სახელი'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ka',
            field=models.CharField(max_length=100, null=True, verbose_name='სახელი'),
        ),
    ]
