# Generated by Django 5.1.2 on 2024-11-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_product_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(default='Default Name', max_length=100, null=True, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_ka',
            field=models.CharField(default='Default Name', max_length=100, null=True, verbose_name='სახელი'),
        ),
    ]
