# Generated by Django 5.1.2 on 2024-11-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description_ka',
        ),
    ]
