# Generated by Django 5.1.2 on 2024-11-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_product_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='სახელი'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ka',
            field=models.CharField(max_length=100, null=True, verbose_name='სახელი'),
        ),
    ]
