# Generated by Django 5.1.2 on 2024-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_category_name_en_category_category_name_ka'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttags',
            name='tag_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='სახელი'),
        ),
        migrations.AddField(
            model_name='producttags',
            name='tag_name_ka',
            field=models.CharField(max_length=150, null=True, verbose_name='სახელი'),
        ),
    ]
